package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "users")
data class UserEntity(
    @PrimaryKey val id: Int = 1,
    val name: String,
    val role: String, // "TRAVELER" or "HOST"
    val walletBalanceYer: Double,
    val walletBalanceUsd: Double,
    val rewardPoints: Int
)

@Entity(tableName = "experiences")
data class ExperienceEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val titleAr: String,
    val titleEn: String,
    val descriptionAr: String,
    val descriptionEn: String,
    val categoryAr: String,
    val categoryEn: String,
    val cityAr: String,
    val cityEn: String,
    val priceYer: Double,
    val priceUsd: Double,
    val durationHours: Int,
    val maxParticipants: Int,
    val hostNameAr: String,
    val hostNameEn: String,
    val isCustomCreated: Boolean = false,
    val iconName: String = "default"
)

@Entity(tableName = "bookings")
data class BookingEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val type: String, // "EXPERIENCE", "CAR", "GUIDE"
    val targetId: Long,
    val titleAr: String,
    val titleEn: String,
    val bookingDate: String,
    val quantity: Int,
    val totalPriceYer: Double,
    val totalPriceUsd: Double,
    val status: String, // "CONFIRMED", "COMPLETED"
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "tour_guides")
data class TourGuideEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val nameAr: String,
    val nameEn: String,
    val cityAr: String,
    val cityEn: String,
    val languagesAr: String,
    val languagesEn: String,
    val rating: Double,
    val pricePerDayYer: Double,
    val pricePerDayUsd: Double,
    val isBooked: Boolean = false
)

@Entity(tableName = "car_rentals")
data class CarRentalEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val model: String,
    val typeAr: String,
    val typeEn: String,
    val capacity: Int,
    val pricePerDayYer: Double,
    val pricePerDayUsd: Double,
    val isRented: Boolean = false
)

@Entity(tableName = "itineraries")
data class ItineraryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val titleAr: String,
    val titleEn: String,
    val budgetLevel: String, // "LOW", "MEDIUM", "HIGH"
    val durationDays: Int,
    val interests: String,
    val responseText: String, // Full text generated by Gemini AI
    val timestamp: Long = System.currentTimeMillis()
)
